name: Optimize Images
on: [ push, pull_request ]
jobs:
  optimize_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Image Optimizer
        uses: crush-pics/crush-pics-github-action@v1
